# Generated by Django 4.1.2 on 2022-10-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("con_id_pk", models.AutoField(primary_key=True, serialize=False)),
                ("con_sn", models.CharField(max_length=70, verbose_name="SN")),
                (
                    "con_onu_type",
                    models.CharField(max_length=100, verbose_name="ONU TYPE"),
                ),
                (
                    "con_cod_contrato",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Código de Contrato"
                    ),
                ),
                (
                    "con_nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Cliente"),
                ),
                ("con_zona", models.CharField(max_length=100, verbose_name="Zona")),
                (
                    "con_direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                ("con_odb", models.CharField(max_length=100, verbose_name="ODB")),
                ("con_status", models.CharField(max_length=100, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("rep_id_pk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rep_pro_reportado",
                    models.CharField(max_length=200, verbose_name="Problema Reportado"),
                ),
                (
                    "rep_pro_tecnico",
                    models.CharField(max_length=200, verbose_name="Problema Tècninico"),
                ),
                ("rep_estado", models.CharField(max_length=100, verbose_name="Estado")),
                (
                    "rep_potencia",
                    models.CharField(max_length=70, verbose_name="Potencia"),
                ),
                (
                    "rep_ab_mikrotik",
                    models.CharField(max_length=70, verbose_name="AB Mikrotik"),
                ),
                ("rep_observaciones", models.TextField(verbose_name="Observaciones")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
                (
                    "Contrato_con_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Contrato",
                        to="soportesLivingNet.contrato",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
            },
        ),
    ]
