# Generated by Django 4.1.2 on 2022-10-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Casa",
            fields=[
                ("cas_id_pk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cas_tipo",
                    models.CharField(max_length=30, verbose_name="Tipo de casa"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Casa",
                "verbose_name_plural": "Tipos de Casas",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("con_id_pk", models.AutoField(primary_key=True, serialize=False)),
                ("con_sn", models.CharField(max_length=70, verbose_name="SN")),
                (
                    "con_onu_type",
                    models.CharField(max_length=100, verbose_name="ONU TYPE"),
                ),
                (
                    "con_cod_contrato",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Código de Contrato"
                    ),
                ),
                (
                    "con_nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Cliente"),
                ),
                ("con_zona", models.CharField(max_length=100, verbose_name="Zona")),
                (
                    "con_direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                ("con_odb", models.CharField(max_length=100, verbose_name="ODB")),
                ("con_status", models.CharField(max_length=100, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("equ_id_pk", models.AutoField(primary_key=True, serialize=False)),
                ("equ_nombre", models.CharField(max_length=30, verbose_name="Equipo")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("rep_id_pk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rep_pro_reportado",
                    models.CharField(max_length=200, verbose_name="Pro. Reportado"),
                ),
                (
                    "rep_pro_tecnico",
                    models.CharField(max_length=200, verbose_name="Pro. Tècninico"),
                ),
                (
                    "rep_estado",
                    models.CharField(
                        choices=[
                            ("SOLUCIONADO", "SOLUCIONADO"),
                            ("PENDIETE", "PENDIETE"),
                            ("OBSERVACIONES", "OBSERVACIONES"),
                        ],
                        default="PENDIETE",
                        max_length=100,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "rep_pon",
                    models.CharField(
                        choices=[
                            ("PON 1", "PON 1"),
                            ("PON 2", "PON 2"),
                            ("PON 3", "PON 3"),
                            ("PON 4", "PON 4"),
                            ("PON 5", "PON 5"),
                            ("PON 6", "PON 6"),
                            ("PON 7", "PON 7"),
                            ("PON 8", "PON 8"),
                            ("PON 9", "PON 9"),
                            ("PON 10", "PON 10"),
                            ("PON 11", "PON 11"),
                            ("PON 12", "PON 12"),
                            ("PON 13", "PON 13"),
                            ("PON 14", "PON 14"),
                            ("PON 15", "PON 15"),
                            ("PON 16", "PON 16"),
                            ("PON 17", "PON 17"),
                            ("PON 18", "PON 18"),
                            ("PON 19", "PON 19"),
                            ("PON 20", "PON 20"),
                            ("PON 21", "PON 21"),
                            ("PON 22", "PON 22"),
                            ("PON 23", "PON 23"),
                            ("PON 24", "PON 24"),
                            ("PON 25", "PON 25"),
                            ("PON 26", "PON 26"),
                            ("PON 27", "PON 27"),
                            ("PON 28", "PON 28"),
                            ("PON 29", "PON 29"),
                            ("PON 30", "PON 30"),
                            ("PON 31", "PON 31"),
                            ("PON 32", "PON 32"),
                            ("PON 33", "PON 33"),
                            ("PON 34", "PON 34"),
                            ("PON 35", "PON 35"),
                            ("PON 36", "PON 36"),
                            ("PON 37", "PON 37"),
                            ("PON 38", "PON 38"),
                            ("PON 39", "PON 39"),
                            ("PON 40", "PON 40"),
                            ("PON 41", "PON 41"),
                            ("PON 42", "PON 42"),
                            ("PON 43", "PON 43"),
                            ("PON 44", "PON 44"),
                            ("PON 45", "PON 45"),
                            ("PON 46", "PON 46"),
                            ("PON 47", "PON 47"),
                            ("PON 48", "PON 48"),
                            ("PON 49", "PON 49"),
                            ("PON 50", "PON 50"),
                            ("PON 51", "PON 51"),
                            ("PON 52", "PON 52"),
                            ("PON 53", "PON 53"),
                            ("PON 54", "PON 54"),
                            ("PON 55", "PON 55"),
                            ("PON 56", "PON 56"),
                            ("PON 57", "PON 57"),
                            ("PON 58", "PON 58"),
                            ("PON 59", "PON 59"),
                            ("PON 60", "PON 60"),
                            ("PON 61", "PON 61"),
                            ("PON 62", "PON 62"),
                            ("PON 63", "PON 63"),
                            ("PON 64", "PON 64"),
                        ],
                        max_length=15,
                        verbose_name="PON",
                    ),
                ),
                (
                    "rep_potencia_entrada",
                    models.CharField(max_length=70, verbose_name="Pot Entrada"),
                ),
                (
                    "rep_potencia_salida",
                    models.CharField(max_length=70, verbose_name="Pot Salida"),
                ),
                (
                    "rep_ndispositivos",
                    models.IntegerField(verbose_name="N° Dispositivos"),
                ),
                (
                    "rep_ab_mikrotik",
                    models.CharField(max_length=70, verbose_name="AB Mikrotik"),
                ),
                ("rep_observaciones", models.TextField(verbose_name="Observaciones")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
                (
                    "Casa_cas_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Casa",
                        to="soportesLivingNet.casa",
                        verbose_name="Tipo de Casa",
                    ),
                ),
                (
                    "Contrato_con_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Contrato",
                        to="soportesLivingNet.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "Equipo_equ_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipo",
                        to="soportesLivingNet.equipo",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
            },
        ),
    ]
