# Generated by Django 4.1.2 on 2022-10-19 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Casa",
            fields=[
                ("cas_id_pk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cas_tipo",
                    models.CharField(max_length=30, verbose_name="Tipo de casa"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Casa",
                "verbose_name_plural": "Tipos de Casas",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                ("con_id_pk", models.AutoField(primary_key=True, serialize=False)),
                ("con_sn", models.CharField(max_length=70, verbose_name="SN")),
                (
                    "con_onu_type",
                    models.CharField(max_length=100, verbose_name="ONU TYPE"),
                ),
                (
                    "con_cod_contrato",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Código de Contrato"
                    ),
                ),
                (
                    "con_nombre",
                    models.CharField(max_length=100, verbose_name="Nombre del Cliente"),
                ),
                ("con_zona", models.CharField(max_length=100, verbose_name="Zona")),
                (
                    "con_direccion",
                    models.CharField(max_length=100, verbose_name="Dirección"),
                ),
                ("con_odb", models.CharField(max_length=100, verbose_name="ODB")),
                ("con_status", models.CharField(max_length=100, verbose_name="Estado")),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
            },
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("equ_id_pk", models.AutoField(primary_key=True, serialize=False)),
                ("equ_nombre", models.CharField(max_length=30, verbose_name="Equipo")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                ("rep_id_pk", models.AutoField(primary_key=True, serialize=False)),
                (
                    "rep_pro_reportado",
                    models.CharField(max_length=200, verbose_name="Problema Reportado"),
                ),
                (
                    "rep_pro_tecnico",
                    models.CharField(max_length=200, verbose_name="Problema Tècninico"),
                ),
                (
                    "rep_estado",
                    models.CharField(
                        choices=[
                            ("SOLUCIONADO", "SOLUCIONADO"),
                            ("PENDIETE", "PENDIETE"),
                            ("OBSERVACIONES", "OBSERVACIONES"),
                        ],
                        default="PENDIETE",
                        max_length=100,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "rep_pon",
                    models.CharField(
                        choices=[
                            (85, 85),
                            (90, 90),
                            (95, 95),
                            (100, 100),
                            (105, 105),
                            (110, 110),
                            (115, 115),
                            (120, 120),
                            (125, 125),
                            (130, 130),
                            (135, 135),
                            (140, 140),
                            (145, 145),
                        ],
                        max_length=15,
                        verbose_name="PON",
                    ),
                ),
                (
                    "rep_potencia_entrada",
                    models.CharField(max_length=70, verbose_name="Potencia de Entrada"),
                ),
                (
                    "rep_potencia_salida",
                    models.CharField(max_length=70, verbose_name="Potencia deSalida"),
                ),
                (
                    "rep_ndispositivos",
                    models.IntegerField(verbose_name="N° Dispositivos"),
                ),
                (
                    "rep_ab_mikrotik",
                    models.CharField(max_length=70, verbose_name="AB Mikrotik"),
                ),
                ("rep_observaciones", models.TextField(verbose_name="Observaciones")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de edición"
                    ),
                ),
                (
                    "Casa_cas_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Casa",
                        to="soportesLivingNet.casa",
                        verbose_name="Tipo de Casa",
                    ),
                ),
                (
                    "Contrato_con_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Contrato",
                        to="soportesLivingNet.contrato",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "Equipo_equ_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Equipo",
                        to="soportesLivingNet.equipo",
                        verbose_name="Equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte",
                "verbose_name_plural": "Reportes",
            },
        ),
    ]
