# Generated by Django 4.1.2 on 2022-11-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soportesLivingNet", "0003_alter_reporte_problemaconfirmado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporte",
            name="rep_imagen",
            field=models.FileField(
                blank=True, null=True, upload_to="documentos/", verbose_name="Imagen"
            ),
        ),
    ]
